/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CaseCard: typeof import('./src/components/CaseCard.vue')['default']
    CaseFormModal: typeof import('./src/components/CaseFormModal.vue')['default']
    CaseModal: typeof import('./src/components/CaseModal.vue')['default']
    GoogleLoginModal: typeof import('./src/components/GoogleLoginModal.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const CaseCard: typeof import('./src/components/CaseCard.vue')['default']
  const CaseFormModal: typeof import('./src/components/CaseFormModal.vue')['default']
  const CaseModal: typeof import('./src/components/CaseModal.vue')['default']
  const GoogleLoginModal: typeof import('./src/components/GoogleLoginModal.vue')['default']
  const Navbar: typeof import('./src/components/Navbar.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}